name: recurrDepl
on: 
  workflow_call:
    inputs:
      artifact-namen:
        description: The name forartifact
        type: string
        default: valz
jobs:
    deploying:
        runs-on: ubuntu-latest
        steps:
          - name: Say bye
            run: ${{ inputs.artifact-namen }}