name: 2ndaxn
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, closed] # when PR
    branches: ["main"] # pull request targets main
  push:
    branches: ["main"] # when PR is merged to main this is also triggered
    paths-ignore:
      - '.github/worklfows/**'
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Run tests
        run: npm run test:ci 
  Building:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Build
        run: npm run build
      - name: upload artifactory
        uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path: dist/first-proj
      # {6}

  Deploy:
    needs: [Testing,Building]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploying
        run: echo deploying...
      - name: expressing
        run: echo "${{ toJSON(github)}}"