name: 2ndaxn
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Run tests
        run: npm run test:ci 
      # {6}
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build