name: 2ndaxn
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci
      - name: Build
        run: npm run build