name: 2ndaxn
on: 
  push:
   branches: ["main"]
   paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
  pull_request:
    types: [opened, closed] # when PR is opened or closed
    branches: ["main"] # pull request targets main
  
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Run tests
        run: npm run test:ci 
      # {6}
  Deploy:
    needs: [Testing]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: |
          echo "Hello"
          echo "World"
      - name: Say bye
        run: echo "Audweidersehen"
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploying
        run: echo deploying...
      - name: expressing
        run: echo "${{ toJSON(github)}}"